apiVersion: v1
kind: Namespace
metadata:
  name: attendance-system
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: attendance-system
data:
  DEBUG: "False"
  DATABASE_URL: "postgres://postgres:postgres@db-service:5432/attendance"
  ALLOWED_HOSTS: "*"
  SECRET_KEY: "NishanthKJ"
  DB_PASSWORD: "postgres"
